version: 1.0.{build}
image: Visual Studio 2017
environment:
  nugetKey:
    secure: xYfI50kUX3/B3JgULd2wsy5C8ofRT5+BLUNj/fLbxJSZdecJn7HTElb6p5obvNeY
build_script:
- cmd: >-
    dotnet restore


    dotnet build -c Release


    dotnet pack -c Release
artifacts:
- path: sharpcorefilesystem/bin/release/*
  name: sharpfilesystem
deploy:
- provider: NuGet
  api_key:
    secure: xYfI50kUX3/B3JgULd2wsy5C8ofRT5+BLUNj/fLbxJSZdecJn7HTElb6p5obvNeY
