version: 1.0.{build}
image: Visual Studio 2017
environment:
  nugetKey: oy2elmciui62sswadljqreyzkjkluwjerovbayu7r2dcw4
build_script:
- cmd: >-
    dotnet restore


    dotnet build -c Release


    dotnet pack -c Release
artifacts:
- path: sharpfilesystem/bin/release/*
  name: sharpfilesystem
