version: 1.0.{build}
image: Visual Studio 2017
environment:
  nugetKey:
    secure: jlkQ4lJxiapfC87YZMljFZbeROpo26F7wbEB7q+xn5xWlAyfOvy/SNrji8a5uKap
build_script:
- cmd: >-
    dotnet restore


    dotnet build -c Release


    dotnet pack -c Release
test_script:
- cmd: dotnet test SharpFileSystem.Tests/SharpFileSystem.Tests.csproj
artifacts:
- path: sharpcorefilesystem/bin/release/*
  name: sharpfilesystem
deploy:
- provider: NuGet
  api_key:
    secure: jlkQ4lJxiapfC87YZMljFZbeROpo26F7wbEB7q+xn5xWlAyfOvy/SNrji8a5uKap