version: 1.0.{build}
image: Visual Studio 2017
environment:
  nugetKey:
    secure: Ik0QjCJ0yNqLI5QRup+5eG9wkP38rJkPAYd/fbk8vUcBnO/5qi5U9O7Q1K312d9Z
build_script:
- cmd: >-
    dotnet restore


    dotnet build -c Release


    dotnet pack -c Release
artifacts:
- path: sharpcorefilesystem/bin/release/*
  name: sharpcorefilesystem
